services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perfume_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - perfume-network

networks:
  perfume-network:
    driver: bridge
